name: Flake 8

on: [push]

jobs:
  flake-lint:
    runs-on: ubuntu-latest
    name: Flake Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Lint
        uses: py-actions/flake8@v2
        with:
          label: Flake
