name: MyPy

on: [push]

jobs:
  mypy-lint:
    runs-on: ubuntu-latest
    name: MyPy Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Mypy Check
        run: |
          python -m pip install --upgrade pip
          pip install mypy==1.1.1 mypy-extensions==1.0.0
          python -m pip install types-PyYAML
          mypy --install-types --non-interactive --config-file pyproject.toml .
