name: Ruff

on: [push]

jobs:
  ruff-lint:
    runs-on: ubuntu-latest
    name: Ruff Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Lint
        uses: jpetrucciani/ruff-check@main
